
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kalpana
 */
public class Time_table extends javax.swing.JFrame {
Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public Time_table() {
        initComponents();
        
        try{
        //GET THE CONNECTION TO THE DATABASE 
         conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/school","root","kalpana");
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox41 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox42 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        time = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBox27.setText("9.00 am - 3.00 pm");

        jCheckBox28.setText("1.00 pm - 4.00 pm");

        jCheckBox29.setText("1.30 pm - 6.30 pm");

        jCheckBox30.setText("5.00 pm - 8.00 pm");

        jCheckBox31.setText("8.30 am - 1.30 pm");

        jCheckBox32.setText("9.00 am - 12.00 pm");

        jCheckBox33.setText("9.00 am - 3.00 pm");

        jCheckBox34.setText("1.00 pm - 4.00 pm");

        jCheckBox35.setText("1.30 pm - 6.30 pm");

        jCheckBox36.setText("5.00 pm - 8.00 pm");

        jLabel8.setText("Monday");

        jLabel9.setText("Tuesday");

        jLabel10.setText("Wednesday");

        jLabel6.setText("Scheduling ");

        jCheckBox37.setText("8.30 am - 1.30 pm");

        jCheckBox38.setText("9.00 am - 12.00 pm");

        jCheckBox39.setText("9.00 am - 3.00 pm");

        jCheckBox40.setText("1.00 pm - 4.00 pm");

        jLabel11.setText("Thursday");

        jCheckBox41.setText("1.30 pm - 6.30 pm");

        jLabel12.setText("Friday");

        jCheckBox42.setText("5.00 pm - 8.00 pm");

        jLabel13.setText("Saturday");

        jLabel14.setText("Sunday");

        jCheckBox1.setText("8.30 am - 1.30 pm");

        jCheckBox2.setText("9.00 am - 12.00 pm");

        jCheckBox3.setText("9.00 am - 3.00 pm");

        jCheckBox4.setText("1.00 pm - 4.00 pm");

        jCheckBox5.setText("1.30 pm - 6.30 pm");

        jCheckBox6.setText("5.00 pm - 8.00 pm");

        jCheckBox7.setText("8.30 am - 1.30 pm");

        jCheckBox8.setText("9.00 am - 12.00 pm");

        jCheckBox9.setText("9.00 am - 3.00 pm");

        jCheckBox10.setText("1.00 pm - 4.00 pm");

        jCheckBox11.setText("1.30 pm - 6.30 pm");

        jCheckBox12.setText("5.00 pm - 8.00 pm");

        jCheckBox13.setText("8.30 am - 1.30 pm");

        jCheckBox14.setText("9.00 am - 12.00 pm");

        jCheckBox15.setText("9.00 am - 3.00 pm");

        jCheckBox16.setText("1.00 pm - 4.00 pm");

        jCheckBox17.setText("1.30 pm - 6.30 pm");

        jCheckBox18.setText("5.00 pm - 8.00 pm");

        jCheckBox19.setText("8.30 am - 1.30 pm");

        jCheckBox20.setText("9.00 am - 12.00 pm");

        jCheckBox21.setText("9.00 am - 3.00 pm");

        jCheckBox22.setText("1.00 pm - 4.00 pm");

        jCheckBox23.setText("1.30 pm - 6.30 pm");

        jCheckBox24.setText("5.00 pm - 8.00 pm");

        jCheckBox25.setText("8.30 am - 1.30 pm");

        jCheckBox26.setText("9.00 am - 12.00 pm");

        time.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null},
                {"2", null, null, null}
            },
            new String [] {
                "", "Check 1", "Check 2", "Che"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(time);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel14)
                                .addComponent(jLabel9)
                                .addComponent(jLabel13)
                                .addComponent(jLabel8))
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCheckBox13)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox14)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox15)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox16)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox17)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCheckBox7)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox8)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox9)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox10)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox11)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox12))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCheckBox19)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox20)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox21)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox22)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox23)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox24))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCheckBox25)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox26)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox27)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox28)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox29)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox30))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCheckBox31)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox32)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox33)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox34)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox35)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox36))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCheckBox37)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox38)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox39)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox40)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox41)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox42))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jCheckBox1)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox2)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox3)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox4)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox5)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCheckBox6)))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(402, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jCheckBox1)
                        .addComponent(jCheckBox2)
                        .addComponent(jCheckBox3)
                        .addComponent(jCheckBox4)
                        .addComponent(jCheckBox5)
                        .addComponent(jCheckBox6)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jCheckBox7)
                        .addComponent(jCheckBox8)
                        .addComponent(jCheckBox9)
                        .addComponent(jCheckBox10)
                        .addComponent(jCheckBox11)
                        .addComponent(jCheckBox12))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jCheckBox13)
                        .addComponent(jCheckBox14)
                        .addComponent(jCheckBox15)
                        .addComponent(jCheckBox16)
                        .addComponent(jCheckBox17)
                        .addComponent(jCheckBox18))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jCheckBox19)
                        .addComponent(jCheckBox20)
                        .addComponent(jCheckBox21)
                        .addComponent(jCheckBox22)
                        .addComponent(jCheckBox23)
                        .addComponent(jCheckBox24))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jCheckBox25)
                        .addComponent(jCheckBox26)
                        .addComponent(jCheckBox27)
                        .addComponent(jCheckBox28)
                        .addComponent(jCheckBox29)
                        .addComponent(jCheckBox30))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox31)
                        .addComponent(jCheckBox32)
                        .addComponent(jCheckBox33)
                        .addComponent(jCheckBox34)
                        .addComponent(jCheckBox35)
                        .addComponent(jCheckBox36)
                        .addComponent(jLabel13))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox37)
                        .addComponent(jCheckBox38)
                        .addComponent(jCheckBox39)
                        .addComponent(jCheckBox40)
                        .addComponent(jCheckBox41)
                        .addComponent(jCheckBox42)
                        .addComponent(jLabel14))
                    .addContainerGap(189, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
           
                    String sql="insert into check (check1,check2,check)values(?,?,?)";

                    pst=conn.prepareStatement(sql);
                    int r=time.getSelectedRow();
                    String c=time.getModel().getValueAt(r, 0).toString();
                  
                    if(Boolean.TRUE.equals((Boolean)time.getModel().getValueAt(r, 1))) {
                        pst.setString(1, c );
                        }
                    
                    if(Boolean.TRUE.equals((Boolean)time.getModel().getValueAt(r, 2))) {
                        pst.setString(2, c );
                        }
                    
                    if(Boolean.TRUE.equals((Boolean)time.getModel().getValueAt(r, 3))) {
                        pst.setString(3, c );
                        }
                    
                        pst.executeUpdate();
                        pst.close();
                        JOptionPane.showMessageDialog(null, "Successfully Inserted");
                    
                    System.out.println();
                
            
       }
       catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
                }
        
 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Time_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Time_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Time_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Time_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Time_table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable time;
    // End of variables declaration//GEN-END:variables
}
